name: Hello World
description: Greets you by name!
slug: hello_world

builder: docker
builderConfig:
  dockerfile: Dockerfile

arguments: ["{{.name}}"]
parameters:
  - name: Name
    slug: name
    type: string
    default: World
