name: Hello World
description: Greets you by name!

builder: docker
builderConfig:
  dockerfile: Dockerfile

arguments: ["--name", "{{.name}}"]
parameters:
  - name: Name
    slug: name
    type: string
    default: World
