name: Hello World
slug: hello_world
description: Greets you by name!

builder: docker
builderConfig:
  dockerfile: Dockerfile

arguments: ["{{.name}}"]
parameters:
  - name: Name
    slug: name
    type: string
    default: World
